update ci.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -6,30 +6,26 @@ on:
   pull_request:
     branches: [ "master" ]
 
+permissions:
+  contents: read
+  issues: read
+  checks: write
+  pull-requests: write    
+
 # This workflow will build a .NET project
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    # Map a step output to a job output
-    # outputs:
-    #   version: ${{ steps.get-version.outputs.version }}
 
     steps:
     - uses: actions/checkout@v3
-      # with: 
-      #   fetch-depth: 0
 
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 7.0.x
-
-    # - name: add git credentials
-    #   run: |
-    #     git config --global user.name "github-actions[bot]"
-    #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
     - name: Restore dependencies
       run: dotnet restore 
@@ -38,17 +34,19 @@ jobs:
       run: dotnet build  --no-restore --configuration Release
       
     - name: Test
-      run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx"
+      run: dotnet test --no-build --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
 
-    - name: add git credentials
-      run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"      
 
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
+    - name: Publish Test Results
+      uses: EnricoMi/publish-unit-test-result-action/composite@v2
+      if: always()
       with:
-        name: DOTNET Tests                      # Name of the check run which will be created
-        path: test/UnitTest/TestResults/*.trx    # Path to test results
-        reporter: dotnet-trx                    # Format of test results
+        files: test/UnitTest/TestResults/*.trx
+
+    # - name: Test Report
+    #   uses: dorny/test-reporter@v1
+    #   if: success() || failure()    # run this step even if previous step failed
+    #   with:
+    #     name: DOTNET Tests                      # Name of the check run which will be created
+    #     path: test/UnitTest/TestResults/*.trx    # Path to test results
+    #     reporter: dotnet-trx                    # Format of test results
